config/routes.rb
Rails.application.routes.draw do
  resources :products
  root to: 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
 
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    respond_to do |format|
      format.html do
        # load records for the HTML view (adjust ordering/limit or add pagination as needed)
        @products = Product.includes(:category).order(created_at: :desc).limit(50)
      end
      format.json { render json: ProductsDatatable.new(view_context) }
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsDatatable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>DataTables Products</h1>

<table id="products" class="display" data-source="<%= products_url(format: "json") %>">
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Category</th>
      <th>Release Date</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Released on:</b>
  <%= @product.released_on.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category.name %>
</p>

<%= link_to 'Back', products_path %>